
# Get all books
GET http://[::1]:26751/books HTTP/1.1
Content-Type: application/json

###
# Create a book
POST http://[::1]:26751/books HTTP/1.1
Content-Type: application/json

{
    "title":"The Lord of the Rings"
}

###
# Edit a book
PUT http://[::1]:26751/books/1 HTTP/1.1
Content-Type: application/json

{
    "title":"The Silmarillion"
}

###
# Delete a book
DELETE http://[::1]:26751/books/1 HTTP/1.1
Content-Type: application/json
